# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - name: Run Plato
      run: npx plato -r -d report src/
    - name: Commit Plato Report
      run: |
        git add report/
        git commit --amend -m "Update Plato report [skip ci]" || echo "No changes"
    - name: Push Report
      run: git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/bugfrei/UnitTests.git HEAD:main --force
      


  
